# Generated by Django 4.2.6 on 2023-10-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourse',
            old_name='state',
            new_name='status',
        ),
    ]
