# Generated by Django 4.2.6 on 2023-10-28 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_courses', '0002_rename_state_studentcourse_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourse',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='studentcourse',
            old_name='student_id',
            new_name='student',
        ),
    ]
